---
title: "SIR_Trento"
author: "Geir Storvik"
date: "2025-05-13"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## SMC_SIR

Notebook for performing sequential Monte Carlo on SIR model 

### Incidence data


```{r cars}
library(data.table)
library(ggplot2)
x = read.csv("../data/data_covid19_lab_by_time_latest.csv")
df = data.frame(date=as.Date(x$date),npos=x$n_pos)
ggplot(data=df,aes(x=date,y=npos)) + geom_line()
```

### Weekly data

For simplification, we consider weekly data, avoiding seasonality within weeks

```{r weekly, echo=FALSE}
n = nrow(df)
n2 = n%/%7
df2 = df[c(1:n2)*7-3,]
for(i in 1:n2)
{
 df2$npos[i] = sum(df$npos[i*7-7+1:7])
}
ggplot(data=df2,aes(x=date,y=npos)) + geom_line()
```

### SMC
We now want to perform sequential Monte Carlo. We consider the model
$$
a=b
$$
```{r}
simSIR = function(x,bet,gam,h,N)
{
  delta = matrix(nrow=3,ncol=2)
  delta[1,] = c(-1,1)
  delta[2,] = c(0,-1)
  delta[3,] = c(0,0)
  M = as.integer(1/h)
  B = nrow(x)
  print(x)
  for(i in 1:M)
  {
    P = cbind(bet*x[,1]*x[,2]*h/N,gam*x[,2]*h,1-bet*x[,1]*x[,2]*h/N-gam*x[,2]*h)
    print(P)
    for(b in 1:B)
    {
      ind = sample(1:3,1,prob=P[b,])
      x[b,] = x[b,]+delta[ind,]
    }
  }
  x
}
```

```{r SMC,echo=FALSE}
#Population size
npop = 5400000
gamma = 0.5
a=0.9;sigma=1
q=0.5
delta1=1/4
#Number of particles
B = 100000
#Initialization
x = array(NA,c(n2,B,2))
r = matrix(nrow=n2,ncol=B)
x[1,,2] = sample(0:npop,B)     # Prior for number of infected at start
x[1,,1] = npop-x[1,,2]        # Assume no one in R group in the beginning
r[1,] = rnorm(B,0,sigma/sqrt(1-a^2))        # Prior for log(beta/gamma) at first time point
#print(x[1,,])
for(s in 2:n2)
{
 print(s)
 r[s,] = a*r[s-1,]+rnorm(B,0,sigma)
 beta = gamma*exp(r[s,])
 #x[s,,] = simSIR(x[s-1,,],beta,gamma,h=0.000001,npop)
 rate = delta1*beta*x[s-1,,2]/npop
 Inew = rbinom(B,x[s-1,,1],1-exp(-rate))
 Rnew = rbinom(B,x[s-1,,2],delta1*gamma)
 #print(c(df2$npos[2],range(Inew)))
 x[s,,1] = x[s-1,,1]-Inew
 x[s,,2] = x[s-1,,2]+Inew-Rnew
 #print(x[s,,])
 w = dbinom(df2$npos[s],Inew,q)
 #print("w")
 #print(range(w))
 ind = sample(1:B,B,replace=TRUE,prob=w)
 #print(length(unique(ind)))
 x[1:s,,] = x[1:s,ind,]
 r[1:s,] = r[1:s,ind]
}
```


```{r plotSMC,echo=FALSE}
xsum = apply(x[,,2],1,quantile,probs=c(0.025,0.5,0.975))
dfplot = data.frame(date=df2$date,I=xsum[2,])
ggplot(data=dfplot,aes(x=date,y=I)) + geom_line()
```
```{r}
rsum = apply(r,1,quantile,probs=c(0.025,0.5,0.975))
betasum = exp(rsum)
dfplot = data.frame(date=df2$date,betamed=betasum[2,],betaq1=betasum[1,],betaq3=betasum[3,])
ggplot(data=dfplot,aes(x=date)) + geom_line(aes(y=betamed)) + geom_line(aes(y=betaq1),linetype="dashed") + geom_line(aes(y=betaq3),linetype="dashed")
```

