---
title: "SIR_Trento"
author: "Geir Storvik"
date: "2025-05-13"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## SMC_SIR

Notebook for performing sequential Monte Carlo on SIR model 

### Incidence data


```{r cars}
library(data.table)
library(ggplot2)
#x = read.csv("data_covid19_lab_by_time_latest.csv")
df = read.table("../data/Data_Norway.txt",header=T)
df$date = as.Date(df$date)
ggplot(data=df,aes(x=date,y=npos)) + geom_line()
```

### Weekly data

For simplification, we consider weekly data, avoiding seasonality within weeks

```{r weekly, echo=FALSE}
n = nrow(df)
n2 = n%/%7
df2 = df[c(1:n2)*7-3,]
for(i in 1:n2)
{
 df2$nhosp[i] = sum(df$nhosp[i*7-7+1:7],na.rm=TRUE)
 df2$npos[i] = sum(df$npos[i*7-7+1:7],na.rm=TRUE)
 df2$seed[i] = sum(df$seed[i*7-7+1:7],na.rm=TRUE)
}

df2=df2[df2$date>as.Date("2021-07-01"),]
n2=nrow(df2)


ggplot(data=df2,aes(x=date)) + geom_line(aes(y=npos/100))+geom_line(aes(y=nhosp),color="red")+geom_line(aes(y=seed),color="blue")

```

### SMC
We now want to perform sequential Monte Carlo. We consider the model
$$
a=b
$$

```{r SMC,echo=FALSE}
#Population size
npop = 5400000
gamma = 0.33
a=0.95;sigma=0.1
hosp_prob=0.02
q=0.5*hosp_prob
delta1=1/4
#Number of particles
B = 100000
#Initialization
x = array(NA,c(n2,B,2)) #2 states: S and I
r = matrix(nrow=n2,ncol=B)
x[1,,2] = sample(0:npop,B)     # Prior for number of infected at start
x[1,,1] = npop-x[1,,2]         # Assume no one in R group in the beginning

r[1,] = rnorm(B,0,sigma/sqrt(1-a^2))        # Prior for log(beta/gamma) at first time point
#print(x[1,,])
for(s in 2:n2)
{
  flush.console()
  cat(sprintf("\r%d", s))
  #print(s)
  r[s,] = a*r[s-1,]+rnorm(B,0,sigma)
  beta = gamma*exp(r[s,])
  #x[s,,] = simSIR(x[s-1,,],beta,gamma,h=0.000001,npop)
  Inew_weekly=0
  for (day in 1:28){ #7 days
    rate = delta1*beta*(x[s-1,,2])/npop
    Inew = rbinom(B,x[s-1,,1],1-exp(-rate))
    Inew_weekly=Inew_weekly+Inew
    Rnew = rbinom(B,x[s-1,,2],delta1*gamma)
    #print(c(df2$npos[2],range(Inew)))
    x[s,,1] = x[s-1,,1]-Inew
    x[s,,2] = x[s-1,,2]+Inew-Rnew
    #print(x[s,,])
  }
  w = dbinom(df2$nhosp[s],Inew_weekly,q)
  #print("w")
  #print(range(w))
  ind = sample(1:B,B,replace=TRUE,prob=w)
  #print(length(unique(ind)))
  l = max(1,s-10)
  x[l:s,,] = x[l:s,ind,]
  r[l:s,] = r[l:s,ind]
}
```


```{r plotSMC,echo=FALSE}
xsum = apply(x[,,2],1,quantile,probs=c(0.025,0.5,0.975))
dfplot = data.frame(date=df2$date,I=xsum[2,],Iq1=xsum[1,],Iq3=xsum[3,])
ggplot(data=dfplot,aes(x=date))+geom_line(aes(y=I))+geom_line(aes(y=Iq1),linetype="dashed")+geom_line(aes(y=Iq3),linetype="dashed")
#dfplot = data.frame(date=df2$date,I=xsum[2,])
#ggplot(data=dfplot,aes(x=date,y=I)) + geom_line()
```
```{r}
rsum = apply(r,1,quantile,probs=c(0.025,0.5,0.975))
Rsum = exp(rsum)

dfplot = data.frame(date=df2$date,R=Rsum[2,],Rq1=Rsum[1,],Rq3=Rsum[3,])
ggplot(data=dfplot,aes(x=date)) + geom_line(aes(y=R)) + geom_line(aes(y=Rq1),linetype="dashed") + geom_line(aes(y=Rq3),linetype="dashed")
```

