---
title: "SMC_AR"
author: "Geir Storvik"
date: "2025-05-15"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Markdown file for SMC on simple AR-model

$$
\begin{align*}
x_t=&ax_{t-1}+\varepsilon_t,&&\varepsilon_t\stackrel{iid}{\sim}N(0,\sigma_x^2)\\
y_t=&x_t+\eta_t,&&\eta_t\stackrel{iid}{\sim}N(0,\sigma_y^2)\\
\end{align*}
$$
### Simulate data

```{r sim,echo=FALSE}
a=0.9;sigma.x = 0.5;sigma.y=0.3
nT = 100
x = rep(NA,nT)
x[1] = rnorm(1,0,sigma.x/sqrt(1-a^2))
for(i in 2:nT)
 x[i] = a*x[i-1]+rnorm(1,0,sigma.x)
y = x + rnorm(nT,0,sigma.y)
```

### Plot data



```{r plot, echo=FALSE}
df = data.frame(date=1:nT,x=x,y=y)
ggplot(data=df,aes(x=date)) + geom_line(aes(y=x)) + geom_point(aes(y=y))
```
### SMC assuming parameters are known

```{r SMC,echo=FALSE}
SMC = function(y,B,a=0.9,sigma.x=0.5,sigma.y=0.3)
{
 nt = length(y)
 xsim = matrix(nrow=nT,ncol=B)
 #initialization
 xsim[1,] = rnorm(B,0,sigma.x/sqrt(1-a^2))
 w = dnorm(y[1],xsim[1,],sigma.y)
 loglik = log(mean(w))
 for(i in 2:nT)
 {
  # Resample
  ind = sample(1:B,B,prob=w,replace=T)
  xsim[1:(i-1),] = xsim[1:(i-1),ind]
  #Proposals
  xsim[i,] = rnorm(B,a*xsim[i-1,],sigma.x)
  w = dnorm(y[i],xsim[i,],sigma.y)
  loglik = loglik + log(mean(w))
 }
 #Resample last time-point
 ind = sample(1:B,B,prob=w,replace=T)
 xsim = xsim[,ind]
 return(list(xsim=xsim,loglik=loglik))
}
res = SMC(y,B=10000)
xsim = res$xsim
```

### Plotting results

```{r SMCplot}
xsum = apply(xsim,1,quantile,probs=c(0.025,0.5,0.975))
dfplot = data.frame(date=1:nT,xmed=xsum[2,],xq1=xsum[1,],xq3=xsum[3,],xtrue=x)
ggplot(data=dfplot,aes(x=date)) + geom_line(aes(y=xmed)) + geom_line(aes(y=xq1),linetype="dashed") + geom_line(aes(y=xq3),linetype="dashed")+ geom_point(aes(y=xtrue),color="red")
```

### Estimate likelihood
```{r likelihood,echo=FALSE}
asim = seq(-0.95,0.95,length=100)
logliksim = rep(NA,length(asim))
for(l in 1:length(asim))
  logliksim[l] = SMC(y,B=100,a=asim[l])$loglik
plot(asim,logliksim)
```

### PMCMC

Using log-transforms on variances and logit-transform on a

```{r pmcmc, echo=FALSE}
M=1000
atrans = function(rho){(exp(rho)-1)/(exp(rho)+1)}
parsim = matrix(nrow=M,ncol=3)
logliksim = rep(NA,M)
parsim[1,] = 0
rho = 0
logsigx = 0
logsigy = 0

loglik = SMC(y,B=100,a=atrans(parsim[1,1]),
             sigma.x=exp(parsim[1,2]),sigma.y=exp(parsim[1,3]))$loglik
logliksim[1] = loglik
for(m in 2:M)
{
 parprop = parsim[m-1,] + rnorm(3,0,0.1)
 loglikprop = SMC(y,B=100,a=atrans(parprop[1]),
             sigma.x=exp(parprop[2]),sigma.y=exp(parprop[3]))$loglik
 r = loglikprop-loglik
 if(runif(1)<exp(r))
 {
   parsim[m,] = parprop
   loglik = loglikprop
 }
 else
  parsim[m,] = parsim[m-1,]
 logliksim[m] = loglik
}
```

### Plotting results
```{r}
asim = atrans(parsim[,1])
plot.ts(asim);abline(h=a,lty=2)
sigmasim.x = exp(parsim[,2])
plot.ts(sigmasim.x);abline(h=sigma.x,lty=2)
sigmasim.y = exp(parsim[,3])
plot.ts(sigmasim.y);abline(h=sigma.y,lty=2)
#plot.ts(cbind(asim,sigmasim.x,sigmasim.y))
```

